# Generated by Django 5.2.3 on 2025-06-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_balance_alter_send_reciever_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Code', 'verbose_name_plural': 'Verification Codes'},
        ),
    ]
